version: "3.8"
services:
  api:
    build:
      context: "backend"
      dockerfile: Dockerfile
    stop_signal: SIGINT
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    volumes:
      - db-data:/server/storage
      - yara-rules:/server/rules
  web:
    build:
      context: "yara-integrator"
      dockerfile: Dockerfile
    ports:
      - 3003:3000

volumes:
  db-data:
  yara-rules:
