DROP TABLE IF EXISTS rules;

CREATE TABLE rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL UNIQUE,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);