import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { ChangeEvent, useEffect, useState } from "react";
import { Navbar } from "@/components/navbar/navbar";
import { useUploadForm } from "@/hooks/useFormUpload";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { uploadForm, isSuccess, progress } = useUploadForm(
    process.env.YARA_API_URL ?? "http://127.0.0.1:5000"
  );
  const [apk, setApk] = useState<File>();
  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    if (event.target.files?.length) {
      setApk(event.target.files[0]);
    }
  };
  return (
    <>
      <Navbar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main + " bg-bg"}>
        <form onSubmit={uploadForm}>
          {apk && (
            <div className="w-full bg-primary">
              <span>{apk.name}</span>
            </div>
          )}
          <input type="file" onChange={handleFileChange}></input>
          <button
            onClick={() => {
              if (apk) uploadForm();
            }}
          >
            SCAN
          </button>
        </form>
      </main>
    </>
  );
}
